# Generated by Django 3.0.6 on 2020-06-11 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_whom', models.CharField(max_length=250)),
                ('msg_content', models.CharField(max_length=1000)),
                ('sent_when', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reply_to_messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_whom', models.CharField(max_length=250)),
                ('rly_content', models.CharField(max_length=1000)),
                ('sent_when', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('chat_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='billing.Chat_message')),
            ],
            options={
                'unique_together': {('chat_message', 'from_whom')},
            },
        ),
    ]
