# Generated by Django 3.0.6 on 2020-06-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reply_to_messages',
            unique_together=set(),
        ),
    ]
