# Generated by Django 3.0.6 on 2020-07-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20200707_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_message_likes',
            name='from_whom_dislike',
        ),
        migrations.RemoveField(
            model_name='reply_message_likes',
            name='from_whom_dislike',
        ),
        migrations.AddField(
            model_name='chat_message_likes',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reply_message_likes',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
    ]
